{% set name = "diffpy.labpdfproc" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_labpdfproc/diffpy_labpdfproc-0.3.1.tar.gz
  sha256: 7cc4e1a8bdb33ccb26a47b18a89ff0fd93dc0cc4d09c1cf0faf720b772bf959f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - labpdfproc = diffpy.labpdfproc.labpdfprocapp:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - diffpy.utils
    - pandas
    - scipy
    - gooey

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-mock
  imports:
    - diffpy.labpdfproc
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.labpdfproc/
  summary: A Python package for processing x-ray powder diffraction data from laboratory sources.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    A Python package for processing x-ray powder diffraction data from laboratory sources.
  doc_url: https://diffpy.github.io/diffpy.labpdfproc/
  dev_url: https://github.com/diffpy/diffpy.labpdfproc/

extra:
  recipe-maintainers:
    - sbillinge
    - yucongalicechen
    - cadenmyers13
